### ISSUE TITLE
I got nothing in the LuCi website

### ISSUE THREAD

**Issue by dingk123** [MonwF/luci-app-filebrowser#2]
Like the pic below

![image](https://user-images.githubusercontent.com/10344661/98577001-47648000-22f6-11eb-97a6-f98abed57538.png)

**Comment by MonwF** [comment]
PANDORABOX is not compatible

**Comment by dingk123** [comment]
> PANDORABOX is not compatible

I find a application called "luci-app-fileassistant" works well on PandoraBox. So I replace the web resource with its resource.

**Comment by dingk123** [comment]
Use "luci-app-fileassistant"'s web resources replace the original resources.
